#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    JVM_OK = 0,
    ERR_INVALID_MAGIC,
    ERR_UNSUPPORTED_VERSION,
    ERR_CP_INVALID_TAG,
    ERR_OUT_OF_MEMORY,
    ERR_CLASS_NOT_FOUND,
    ERR_METHOD_NOT_FOUND,
    ERR_STACK_OVERFLOW,
    ERR_NULL_POINTER,
    ERR_ARRAY_BOUNDS,
    ERR_UNIMPLEMENTED_OPCODE,
} JvmError;

#endif /* ERRORS_H */
